include:
  - url: ./extensions.yaml

repos:
  services:
    jsonviewer-init:
      docker:
        registry: docker.io
        image: opencloudeu/web-extensions
        # release notes: https://blog.clamav.net
        tag: json-viewer-1.0.0
        entrypoint: "/bin/sh"
        command: ["-c", "cp -R /usr/share/nginx/html/json-viewer/ /apps"]

services:
  opencloud:
    depends_on:
      jsonviewer-init:
        condition: service_completed_successfully

  jsonviewer-init:
    user: root
    volumes:
      - opencloud-apps:/apps
