repos:
  services:
    externalsites-init:
      docker:
        registry: docker.io
        image: opencloudeu/web-extensions
        # release notes: https://blog.clamav.net
        tag: external-sites-1.0.0
        entrypoint: "/bin/sh"
        command: ["-c", "cp -R /usr/share/nginx/html/external-sites/ /apps"]

services:
  opencloud:
    volumes:
      # external sites needs to have sites configured in the web.yaml
      - ./config/opencloud/apps.yaml:/etc/opencloud/apps.yaml
    depends_on:
      externalsites-init:
        condition: service_completed_successfully

  externalsites-init:
    user: root
    volumes:
      - opencloud-apps:/apps
    networks:
      - opencloud-net
