include:
  - url: ./config.yaml

repos:
  services:
    postgres:
      docker:
        registry: docker.io
        image: library/postgres
        # https://hub.docker.com/_/postgres/tags
        tag: 15.12

services:
  postgres:
    restart: always
    stop_signal: SIGINT

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U penpot"]
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 2s

    volumes:
      - postgres:/var/lib/postgresql/data

    networks:
      - penpot

    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB={{.configs.postgres.db}}
      - POSTGRES_USER={{.configs.postgres.user}}
      - POSTGRES_PASSWORD={{.configs.postgres.password}}

volumes:
  postgres:
  