configs:
  traefik:
    log_level: "ERROR"

repos:
  services:
    traefik:
      docker:
        registry: docker.io
        image: library/traefik
        tag: v3.3.1

services:
  traefik:
    image: "{{.repos.services.traefik.docker.registry}}/{{.repos.services.traefik.docker.image}}:{{.repos.services.traefik.docker.tag}}"
    # release notes: https://github.com/traefik/traefik/releases
    networks:
      opencloud-net:
    command:
      - "--log.level={{.configs.traefik.log_level}}"
      # define entrypoints
      - "--entryPoints.http.address=:80"
      # change default timeouts for long-running requests
      # this is needed for webdav clients that do not support the TUS protocol
      - "--entryPoints.http.transport.respondingTimeouts.readTimeout=12h"
      - "--entryPoints.http.transport.respondingTimeouts.writeTimeout=12h"
      - "--entryPoints.http.transport.respondingTimeouts.idleTimeout=3m"
      # docker provider (get configuration from container labels)
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
      # access log
      - "--accessLog=true"
      - "--accessLog.format=json"
      - "--accessLog.fields.headers.names.X-Request-Id=keep"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${DOCKER_SOCKET_PATH:-/var/run/docker.sock}:/var/run/docker.sock:ro"
      - "certs:/certs"
    logging:
      driver: "{{.configs.opencloud.docker.log_driver}}"
    restart: "{{.configs.opencloud.docker.restart}}"

volumes:
  certs: